version: '2'

services:

    # https://hub.docker.com/_/nginx/
    nginx:
      build:
        context: docker
        dockerfile: Dockerfile.nginx
      container_name: nginx
      volumes:
        - ./campaigner_hot.nginx.conf:/etc/nginx/conf.d/default.conf
      command: nginx -g 'daemon off;'
      ports:
        - 80:80
        - 443:443
      depends_on:
        - web
      networks:
        - code-network

    web:
      #image: kartoza/osm-reporter
      build:
        context: docker
        dockerfile: Dockerfile
      hostname: web
      container_name: osmreporter_web
      environment:
        - PGUSER=docker
        - PGPASSWORD=docker
        - PGHOST=db
        - APP_SETTINGS=app_config.Config
        - DATABASE_URL=postgresql://db/gis
        - DATA_FOLDER=/home/web/field-campaigner-data
        - ATTIC_DATA_SERVER_URL=http://export.hotosm.org:6080/api/interpreter
        - DEFAULT_OVERPASS_URL=http://export.hotosm.org:6080/api/interpreter
      ports:
        - "64000:8080"
      volumes:
        - ../flask_project:/home/web/osm_reporter
        - ../../field-campaigner-data:/home/web/field-campaigner-data
      restart: on-failure:5
      user: root
      networks:
          - code-network

networks:
  code-network:
    driver: bridge
  database-network:
    driver: bridge